#ifndef ASSETBUNDLELOADER_HPP
#define ASSETBUNDLELOADER_HPP

#include <config.h>
#include <string>

class AssetBundle {
  public:
    std::string APP_TITLE = _APP_TITLE;
    std::string ITEM_NULL_NAME = _ITEM_NULL_NAME;
    std::string ITEM_NULL_DESCRIPTION = _ITEM_NULL_DESCRIPTION;
    std::string ITEM_NULL_SPRITE_PATH = _ITEM_NULL_SPRITE_PATH;
    std::string INTERACTABLE_NULL_NAME = _INTERACTABLE_NULL_NAME;
    std::string INTERACTABLE_NULL_SPRITE_PATH = _INTERACTABLE_NULL_SPRITE_PATH;
    int PLAYER_MOVE_SPEED = _PLAYER_MOVE_SPEED;
    std::string HOLE_UNIFIED_TEXTURE_PATH = _HOLE_UNIFIED_TEXTURE_PATH;
    std::string SHOVEL_ITEM_NAME = _SHOVEL_ITEM_NAME;
    std::string SHOVEL_ITEM_DESCRIPTION = _SHOVEL_ITEM_DESCRIPTION;
    std::string SHOVEL_ITEM_SPRITE_PATH = _SHOVEL_ITEM_SPRITE_PATH;
    std::string BOTTLE_ITEM_NAME = _BOTTLE_ITEM_NAME;
    std::string BOTTLE_ITEM_SPRITE_PATH = _BOTTLE_ITEM_SPRITE_PATH;
    std::string FOOD_ITEM_NAME = _FOOD_ITEM_NAME;
    std::string FOOD_ITEM_SPRITE_PATH = _FOOD_ITEM_SPRITE_PATH;
    std::string WATER_REFILL_STATION_NAME = _WATER_REFILL_STATION_NAME;
    std::string WATER_REFILL_STATION_SPRITE_PATH = _WATER_REFILL_STATION_SPRITE_PATH;
    std::string PLAYERSTAT_HEALTH_ICON_PATH = _PLAYERSTAT_HEALTH_ICON_PATH;
    std::string PLAYERSTAT_ENERGY_ICON_PATH = _PLAYERSTAT_ENERGY_ICON_PATH;
    std::string PLAYERSTAT_THIRST_ICON_PATH = _PLAYERSTAT_THIRST_ICON_PATH;
    std::string PLAYERSTAT_FONT_PATH = _PLAYERSTAT_FONT_PATH;
    std::string PLAYER_SPRITE_PATH = _PLAYER_SPRITE_PATH;
    std::string MAP_PART_HILL_PATH = _MAP_PART_HILL_PATH;
    std::string FONT_MENU_HINT_PATH = FONT_PRESET_SPACE_GROTESK;
    std::string MENU_BACKGROUND_PATH = _MENU_BACKGROUND_PATH;
    std::string FONT_GAME_INVENTORY_PATH = FONT_PRESET_SPACE_GROTESK;
    std::string FONT_GAMEOVER_PATH = FONT_PRESET_INTER;
    std::string FONT_GAMEOVER_HINT_PATH = FONT_PRESET_INTER_ITALIC;
    int DIALOUGE_BG_BORDER_THICKNESS = _DIALOUGE_BG_BORDER_THICKNESS;
    std::string FONT_GAME_DIALOUGE_PATH = FONT_PRESET_JERSEY_10;
    std::string FONT_GAME_DIALOUGE_NAME_PATH = FONT_PRESET_JACQUARD;

    auto LoadAssetBundle(const char* path) -> void;
};

extern AssetBundle assetBundle;

#endif // ASSETBUNDLELOADER_HPP
